### ISSUE TITLE
Questions about YTVIS evaluation

### ISSUE THREAD

**Issue by weixi-feng** [pixeli99/TrackDiffusion#10]
Hi,

Thanks for the great work! For the YTVIS results in Table 1, is the model trained on just YTVIS 2021 or a mix of YTVIS 2021 + MOT17? 

Are the numbers reported based on 160 validation videos randomly sampled from YTVIS2021? Could you release these video names for evaluation?

**Comment by pixeli99** [comment]
hi, @weixi-feng 

Sorry for replying so late.

Q1: The results in our tab.1 were trained only on the YTVIS dataset and did not include data from MOT17/20.  

Q2: That's correct. We randomly sampled 160 videos, all of which are from the YTVIS trainset. We have uploaded a txt file recording the video names to the following link(https://drive.google.com/file/d/1fi6FqodZFq1YaqnUcdB2hClaLPEcPLIQ/view?usp=sharing), where you can download it to access the information.

**Comment by KaiChen1998** [comment]
@weixi-feng Feel free to re-open this issue if you have any more questions :)
