### ISSUE TITLE
Confuse of which model need to load?

### ISSUE THREAD

**Issue by guyuchao** [pixeli99/TrackDiffusion#8]
In demo.ipynb, which model should load in "/path/to/your/pretrained_model" and "/path/to/unet"? What is the difference.

**Comment by pixeli99** [comment]
Sorry for causing some confusion. `/path/to/your/pretrained_model` refers to the path of sd-v1.5. Because we fine-tuned the unet, `/path/to/unet` needs to point to the new unet weights instead of loading sd1.5's. I made modifications in `demo.ipynb` for better usage by everyone.
