### ISSUE TITLE
SVD分支的代码是完整的吗

### ISSUE THREAD

**Issue by donghaotian123** [pixeli99/TrackDiffusion#9]
我尝试运行SVD分支的文件，但此分支缺少third party文件夹，main分支的diffusers中似乎缺少unet代码，当我下载最新版本0.30.0的diffusers时，forward函数又缺少cross_attention_kwargs这个参数

**Comment by pixeli99** [comment]
我这边是diffusers 0.24.0的分支，SVD分支确实缺少了unet部分的代码修改，你可以从google drive上下载这部分的修改代码，我最近会更新SVD分支的代码

https://drive.google.com/drive/folders/1pk4lYYMq_oAvBN4BkdILXey4iPKhKOX1?usp=sharing

**Comment by donghaotian123** [comment]
好的，我的代码已经能正常训练测试了，谢谢您 : )

**Comment by Doubiiu** [comment]
> 好的，我的代码已经能正常训练测试了，谢谢您 : )

请问大佬，能简单讲一下需要修改哪些东西才可以跑通么，十分感谢！我现在好像也是“forward函数又缺少cross_attention_kwargs这个参数”这个问题，并且已经是diffusers==0.24.0了

**Comment by donghaotian123** [comment]
> > 好的，我的代码已经能正常训练测试了，谢谢您 : )
> 
> 请问大佬，能简单讲一下需要修改哪些东西才可以跑通么，十分感谢！我现在好像也是“forward函数又缺少cross_attention_kwargs这个参数”这个问题，并且已经是diffusers==0.24.0了

您好，很抱歉，时间有点久了，修改细节我忘记了。关于cross_attention_kwargs这个参数，我应该是下载了主分支提供的diffusers代码（不是通过命令行安装的官方的包），然后将作者提供的4个文件进行替换。不知道能不能解决您的问题，如果还是报错的话我们可以进一步讨论。

**Comment by Doubiiu** [comment]
哦哦哦居然是这种暴力操作吗 我以为是比较友善的第三方override的方式 【捂脸】

> > > 好的，我的代码已经能正常训练测试了，谢谢您 : )
> > 
> > 
> > 请问大佬，能简单讲一下需要修改哪些东西才可以跑通么，十分感谢！我现在好像也是“forward函数又缺少cross_attention_kwargs这个参数”这个问题，并且已经是diffusers==0.24.0了
> 
> 您好，很抱歉，时间有点久了，修改细节我忘记了。关于cross_attention_kwargs这个参数，我应该是下载了主分支提供的diffusers代码（不是通过命令行安装的官方的包），然后将作者提供的4个文件进行替换。不知道能不能解决您的问题，如果还是报错的话我们可以进一步讨论。

**Comment by pixeli99** [comment]
@Doubiiu 对的，需要从上面的 google drive 上下载下替换...确实改的很蠢，当时这个 SVD 只是为了补充下结果所以做的不是很完善，可以暂时先这样用下吧🥺

**Comment by Doubiiu** [comment]
感谢帮助，我已经成功跑通了代码的inference，就是直接替换就行了。
Thanks for your nice assistance. To help others with similar issues, please copy all the files in the Google Drive link above to the installed diffusers package library (e.g. <path_to_diffuers_lib>/models/).
